# Generated by Django 5.1.7 on 2025-03-30 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='distributor.distributor'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
