# Generated by Django 5.1.7 on 2025-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Base User', 'Base User'), ('Admin', 'Admin'), ('Support', 'Support'), ('Manager', 'Manager')], default='Base User', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
