# Generated by Django 5.1.7 on 2025-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_otp_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Base User', 'Base User'), ('Admin', 'Admin'), ('Support', 'Support'), ('Manager', 'Manager'), ('Distributor', 'Distributor'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff')], default='Base User', max_length=20, null=True),
        ),
    ]
