# Generated by Django 5.1.7 on 2025-04-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_alter_branch_distributor_alter_branch_id'),
        ('user', '0006_alter_user_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distributor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='distributor.distributor'),
        ),
    ]
