# Generated by Django 5.1.7 on 2025-04-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distributor',
        ),
    ]
